security:
  oauth2:
    client:
      access-token-uri: https://dev-982933.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-982933.oktapreview.com/oauth2/default/v1/authorize
      client-id: 0oag73438nnXksA8O0h7
      scope: openid profile email
    resource:
      user-info-uri: https://dev-982933.oktapreview.com/oauth2/default/v1/userinfo
      token-info-uri: https://dev-982933.oktapreview.com/oauth2/default/v1/introspect
      prefer-token-info: false
